- name: Hello World Rulebook
  hosts: localhost
  sources:
    - ansible.eda.tick:
        delay: 5

  rules:
    - name: Print Hello World
      condition: true
      action:
        debug:
          msg: "Todo está OK."
